### ISSUE TITLE
zui: incorrect logout with basic auth - the session cookie remains after logout

### ISSUE THREAD

**Issue by andaaron** [project-zot/zui#362]

**Comment by raulkele** [comment]
Caused by project-zot/zot#1632 , because zot logout endpoint could not be hit in specific circumstances, causing weird dangling session cookie behavior in zui

**Comment by andaaron** [comment]
This issue doesn't reproduce with the code in https://github.com/project-zot/zot/pull/1639.
It is likely fixed by https://github.com/project-zot/zot/issues/1632.
