### ISSUE TITLE
Repo cards: show user specific metadata

### ISSUE THREAD

**Issue by andaaron** [project-zot/zui#39]
- is this repo starred by the current user?
- ability to star this repo
- show total star count for this repo
- is this repo bookmarked by the current user?
- ability to bookmark this repo

**Comment by andaaron** [comment]
The bookmarks are already done in both the UI and backend. Stars are only done on backend side. We need to implement the stars on frontend.

**Comment by andaaron** [comment]
@zainkhanh1892, can you please look into this issue. We can circle back to #352 after the fix in the backend.

**Comment by zainkhanh1892** [comment]
@andaaron Hey Andrei, do you want me to integrate the backend as well? Or just base code for the stars.

**Comment by andaaron** [comment]
What do you mean by integrate? Let's have a call and decide how to proceed.
