### ISSUE TITLE
[Bug]: UI/Vulnerabilities: Fixed-In section is not clear what it means, should not hide its content

### ISSUE THREAD

**Issue by mikemccracken** [project-zot/zui#393]
### zot version

v1.4.3

### Describe the bug

when viewing the list of vulns for a given image, there is a button "fixed in", which was not clear at first sight. 
It could be reworded to something like "Tags where this cve has been fixed:" or something even better.

Also, if feasible, this should not require a click to see if there are any such results. at a minimum it could say "tags where it's fixed (3):", or just display the list.

### Screenshots

![image](https://github.com/project-zot/zot/assets/1768106/67db5c1f-6f2c-4bb6-a1aa-d9450a1da83d)

**Comment by mikemccracken** [comment]
OK, that makes sense. I still think it'd be a nice improvement, but it isn't critical. If it's possible to display it inline when it's cached and just show a link when it's not, that'd be fine too. (assuming the cache lives for a while and someone else is likely to see it)

FWIW, from my perspective I would always be interested in this info when looking at the vulns for a tag.

I'd also still like to suggest changing the wording, or at least giving a help tooltip explaining it.

**Comment by andaaron** [comment]
Hi @mikemccracken, do we still need this change after the refactoring of the CVE tiles?

**Comment by mikemccracken** [comment]
Hi, no the new design resolves this. Thanks!
