### ISSUE TITLE
[Feat]: ui/vulnerabilities - increase information density 

### ISSUE THREAD

**Issue by mikemccracken** [project-zot/zui#394]
### Is your feature request related to a problem? Please describe.

the page listing the vulns only shows about 5 at a time on my screen. I have had to review lists of hundreds of cves, and the more that fit on the screen the better

![image](https://github.com/project-zot/zot/assets/1768106/98a0b03f-e8d3-44ee-a0ce-be1ef04d7d5b)

### Describe the solution you'd like

ideally a compact display with one line of text per vuln for maximum eyestrain

**Comment by andaaron** [comment]
We need to come up with a new UX. Also need to think of the implications for mobile/small displays.

**Comment by mikemccracken** [comment]
since this is a big change, https://github.com/project-zot/zot/issues/1999 is a workaround for reviewing larger lists, until the UI work is done

**Comment by andaaron** [comment]
@mikemccracken this has been done in https://github.com/project-zot/zui/pull/409, please let us know your feedback.

**Comment by andaaron** [comment]
@mikemccracken we have another update, merged in https://github.com/project-zot/zui/pull/419 / https://github.com/project-zot/zot/pull/2233

**Comment by mikemccracken** [comment]
I am happy with the current one line layout. it's enough to look at a reasonable sized list, and if there's a huge number then I can use the csv export.
