### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by jangrewe** [project-zot/zui#400]
If anyone is looking for a Dockerfile, here's what Works For Me™:
```
FROM node:20-alpine AS build
WORKDIR /app
ADD . /app
RUN npm install
RUN npm run build

FROM node:20-alpine 
WORKDIR /app
ADD . /app
COPY --from=build /app/build /app/build
RUN npm install -g serve
RUN npm install --omit=dev
CMD ["serve", "-s", "build"]
```

**Comment by rchincha** [comment]
@jangrewe ^ is this if you want to deploy the UI separate from the backend?
Asking because zui is packaged into the zot binary itself, so no need to run separate things.

**Comment by jangrewe** [comment]
Oh, it is? Didn't know that, or rather: didn't find anything in the docs how to access it, so i thought it's separate! 😉

**Comment by jangrewe** [comment]
For anybody else not figuring out how to enable the UI:
```
{
[...]
    "extensions": {
        "ui": {
            "enable": true
        },
    }
}
```
