### ISSUE TITLE
Add "freebsd" as an operating system filter

### ISSUE THREAD

**Issue by dfr** [project-zot/zui#407]
**Is your feature request related to a problem? Please describe.**
I use zot to manage both linux and freebsd images and filtering for freebsd would be useful.

**Describe the solution you'd like**
The 'Operating systems' pane on the 'View all' page should include "freebsd" as well as "windows", "linux".

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by rchincha** [comment]
@dfr close this issue since your PR has been merged?
