### ISSUE TITLE
Clarify intended behavior when user selects and image or a layer from freetype search results

### ISSUE THREAD

**Issue by andaaron** [project-zot/zui#41]
Do we need to implement a details view for an image? Do we need to implement a details view for a layer?
Current mocks only cover a repo. They don't cover an image (image is a repo plus a tag). They don't cover the layer.

**Comment by rchamarthy** [comment]
individual layer search is very remote use case. Unless people already know the hash they usually wont search for a layer. One thing that could be useful is if some one knows a layer hash and wants to know which images actually use this layer, they may want to search by hash. If the search comes in for a hash I would still show all the images that this layer is used in. When the image is clicked we can make provide each layer and potentially its SBOM if available.

**Comment by andaaron** [comment]
That makes sense, thank you.
