### ISSUE TITLE
[ZUI][User meu] two horizontal lines between the username and the "Log Out" button.

### ISSUE THREAD

**Issue by andaaron** [project-zot/zui#424]
**Describe the bug**
See attachment, in case API keys are disabled, there is a double horizontal line in the user menu.

**To Reproduce**
Enable zot with authentication, but with API keys disabled.

**Expected behavior**
There is a single line between the username and the "Log Out" button.

**Screenshots**
![image](https://github.com/project-zot/zui/assets/25718736/56425f9a-422c-4ea7-87e3-b89433f910e2)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by vrajashkr** [comment]
Hi @andaaron , @raulkele, would it be alright if I have a go at this one?
