### ISSUE TITLE
Image vulnerabilities XLSX export fails when the image name is longer than 31 characters

### ISSUE THREAD

**Issue by vrajashkr** [project-zot/zui#429]
**Describe the bug**
When the image name exceeds 31 characters, the XLSX export fails without any visual error.
In the browser console, the following error is seen:
```
Uncaught Error: Sheet names cannot exceed 31 chars
    wA xlsx.mjs:16546
    WM xlsx.mjs:24346
    onClick VulnerabilitiesDetails.jsx:253
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
xlsx.mjs:16546:50
    wA xlsx.mjs:16546
    WM xlsx.mjs:24346
    onClick VulnerabilitiesDetails.jsx:253
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
```

**To Reproduce**
1. Upload an image with a name (repo name + tag) having a length greater than 31 characters to a zot instance.
2. In ZUI, open the image details and navigate to the `Vulnerabilities` tab.
3. Click the export button and select `xlsx` as the option.
4. Observe that nothing happens in the UI.
5. Observe the error in the browser console.

**Expected behavior**
The XLSX should be successfully created and a file download initiated.

**Screenshots**
![image](https://github.com/project-zot/zui/assets/30438425/de67ff67-3cda-4612-a43a-c2e6df445e17)

**Desktop:**
 - OS: Ubuntu 22.04 amd64
 - Browser firefox
 - Version 123.0

**Comment by rchincha** [comment]
@vrajashkr thanks for catching and reporting this.
