### ISSUE TITLE
setup ci/cd, unit test framework

### ISSUE THREAD

**Issue by rchincha** [project-zot/zui#45]
**Is your feature request related to a problem? Please describe.**

Currently, we are focused only on feature development, but currently lacking automated testing.

**Describe the solution you'd like**

Add a framework/workflow to build upon.

**Comment by raulkele** [comment]
I believe we already have a github workflow that runs tests and checks for coverage on every PR.
A unit test framework was integrated together with PRs #65 - #68 
Do we need anything additional to add to the workflow from a testing POV ?

**Comment by rchincha** [comment]
Can we track code coverage? `zot` repo already has all this setup, for reference.

**Comment by raulkele** [comment]
Do you mean adding the coverage to the README ? I can look into what is used for zot and replicate it here.
